language: java

jdk: oraclejdk8

sudo: required

services:
  - docker

env:
  - CUBE_LOGGER_ENABLE=true

# These env variables start 2 parallel builds.
#
# The neat part about this setup is that the unit test suite is usually going to be done before
# the integration test suite, giving you a faster visual feedback on the basic test coverage.
#env:
#  - MVN_COMMAND="mvn clean install -Dmaven.javadoc.skip=true -B -V"
#  - MVN_COMMAND="docker-compose build;mvn verify -P integration"

jobs:
  include:
    - stage: test
      script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"
    - stage: integration
      script:
        docker-compose build;
        mvn dependency:resolve -P integration compile exec:java -Dexec.mainClass="io.bisq.api.app.ApiMain" -Dexec.args="--help";
        docker volume create m2;
        docker container create -v m2:/m2 --name m2helperContainer busybox;
        docker cp ~/.m2/repository m2helperContainer:/m2/;
        docker rm m2helperContainer;
        mvn verify -P integration
